# ETL de Dados de Exercícios

Este notebook apresenta um fluxo completo de **ETL** (Extração, Transformação e Carga) usando Pandas e MySQL.

- **Tratamento dos dados:** leitura do CSV, inspeção da estrutura, verificação de duplicidades, limpeza e consolidação das instruções.
- **Modelagem:** organização dos dados em tabelas de exercícios, equipamentos, partes do corpo, músculos secundários e uma relação muitos-para-muitos.
- **Carga no banco:** criação do esquema relacional e inserção dos DataFrames no MySQL respeitando a ordem das chaves estrangeiras.
- **Análise:** execução de consultas SQL para localizar exercícios por parte do corpo, músculos secundários e equipamentos.

In [187]:
import pandas as pd

In [ ]:

import os


filename = r'D:\project\tratamento de dados\etl-data-exercises\data\exercises(1).csv'
user='root'
password='*'
host='localhost'
port=3306
database='spring_api_system'

MYSQL_URL = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"
df = pd.read_csv(filename)
df = df.rename(columns={'gifUrl': 'gif_url'})

In [189]:
df

,bodyPart,equipment,gif_url,id,name,target,secondaryMuscles/0,secondaryMuscles/1,instructions/0,instructions/1,...,instructions/5,secondaryMuscles/2,instructions/6,instructions/7,secondaryMuscles/3,instructions/8,secondaryMuscles/4,instructions/9,secondaryMuscles/5,instructions/10
0,waist,body weight,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,1,3/4 sit-up,abs,hip flexors,lower back,Lie flat on your back with your knees bent and...,Place your hands behind your head with your el...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,waist,body weight,https://v2.exercisedb.io/image/PERWLDGUxVbpHS,2,45° side bend,abs,obliques,NaN,Stand with your feet shoulder-width apart and ...,Keeping your back straight and your core engag...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,waist,body weight,https://v2.exercisedb.io/image/PLr4yo3j-f1amp,3,air bike,abs,hip flexors,NaN,Lie flat on your back with your hands placed b...,Lift your legs off the ground and bend your kn...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,upper legs,body weight,https://v2.exercisedb.io/image/XPQwM7HECjgNFE,1512,all fours squad stretch,quads,hamstrings,glutes,Start on all fours with your hands directly un...,"Extend one leg straight back, keeping your kne...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,waist,body weight,https://v2.exercisedb.io/image/5nYph4eUGNiEdf,6,alternate heel touchers,abs,obliques,NaN,Lie flat on your back with your knees bent and...,"Extend your arms straight out to the sides, pa...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,chest,body weight,https://v2.exercisedb.io/image/XQn4pU9HRquS2b,2363,wide-grip chest dip on high parallel bars,pectorals,triceps,shoulders,Position yourself on the parallel bars with yo...,Lean forward slightly and lower your body by b...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,waist,body weight,https://v2.exercisedb.io/image/ZLPKUAaiObH-2X,858,wind sprints,abs,quadriceps,hamstrings,Find an open space or a track to perform the e...,Start by standing with your feet shoulder-widt...,...,NaN,calves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,upper legs,body weight,https://v2.exercisedb.io/image/3A5fPe5oCr2EwN,1604,world greatest stretch,hamstrings,glutes,quadriceps,Start in a lunge position with your right foot...,Place your hands on the ground on either side ...,...,Switch sides and repeat the stretch with your ...,calves,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,lower arms,body weight,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,1428,wrist circles,forearms,hands,wrists,Extend your arms straight out in front of you.,Make a fist with both hands.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1323,lower arms,weighted,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,859,wrist rollerer,forearms,biceps,triceps,Attach a weight to one end of a rope or bar.,Hold the other end of the rope or bar with bot...,...,Repeat for the desired number of repetitions.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
df.columns

Index(['bodyPart', 'equipment', 'gif_url', 'id', 'name', 'target',
       'secondaryMuscles/0', 'secondaryMuscles/1', 'instructions/0',
       'instructions/1', 'instructions/2', 'instructions/3', 'instructions/4',
       'instructions/5', 'secondaryMuscles/2', 'instructions/6',
       'instructions/7', 'secondaryMuscles/3', 'instructions/8',
       'secondaryMuscles/4', 'instructions/9', 'secondaryMuscles/5',
       'instructions/10'],
      dtype='str')

In [191]:
df['equipment'].unique()

# Partes do corpo de repetem
# Passos podem se unir em um campo apenas como 1. 2. e 3 etc.

<StringArray>
[         'body weight',                'cable',     'leverage machine',
             'assisted',        'medicine ball',       'stability ball',
                 'band',              'barbell',                 'rope',
             'dumbbell',           'ez barbell',         'sled machine',
 'upper body ergometer',           'kettlebell',      'olympic barbell',
             'weighted',            'bosu ball',      'resistance band',
               'roller',       'skierg machine',               'hammer',
        'smith machine',         'wheel roller',      'stationary bike',
                 'tire',             'trap bar',   'elliptical machine',
     'stepmill machine']
Length: 28, dtype: str

In [192]:
df.duplicated(subset=['id']).sum() # ids não conflitantes
df.duplicated(subset=['name']).sum() # nomes de exercicios não conflitantes

np.int64(6)

## 1. Extração e diagnóstico inicial

Nesta etapa, o arquivo `exercises(1).csv` é carregado para um DataFrame. As células seguintes permitem conhecer as colunas disponíveis, observar os equipamentos e verificar se existem identificadores ou nomes duplicados.

Esse diagnóstico orienta as decisões de tratamento antes da criação das tabelas relacionais.

In [193]:
# Filtrar as colunas de instruções disponíveis no DataFrame
instruction_cols = [c for c in df.columns if c.startswith('instructions/')]

def summarize_instructions(row):
    steps = []
    step_num = 1
    for col in instruction_cols:
        val = row[col]
        if pd.notna(val) and str(val).strip() != '':
            steps.append(f"{step_num}. {str(val).strip()}")
            step_num += 1
    return '\n'.join(steps)

# Criar a nova coluna consolidada
df['instructions_sumarization'] = df.apply(summarize_instructions, axis=1)

# Exibir uma amostra para conferir o resultado
df['instructions_sumarization'][0]

'1. Lie flat on your back with your knees bent and feet flat on the ground.\n2. Place your hands behind your head with your elbows pointing outwards.\n3. Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.\n4. Pause for a moment at the top, then slowly lower your upper body back down to the starting position.\n5. Repeat for the desired number of repetitions.'

## 2. Tratamento e padronização

As colunas de instruções estão distribuídas em vários campos. O tratamento percorre essas colunas, ignora valores vazios e reúne os passos em `instructions_sumarization`, mantendo a ordem original e um formato único para consumo da aplicação.

A partir daqui, o DataFrame deixa de ser apenas uma cópia do CSV e passa a conter um campo preparado para armazenamento e consulta.

In [194]:
table_exercise = df[['name', 'instructions_sumarization', 'gif_url']]
# id de equipamento, id de parte do corpo, tabela n-n para musculos secundarios

In [195]:
table_equipment = df['equipment']
df['equipment'].unique()

<StringArray>
[         'body weight',                'cable',     'leverage machine',
             'assisted',        'medicine ball',       'stability ball',
                 'band',              'barbell',                 'rope',
             'dumbbell',           'ez barbell',         'sled machine',
 'upper body ergometer',           'kettlebell',      'olympic barbell',
             'weighted',            'bosu ball',      'resistance band',
               'roller',       'skierg machine',               'hammer',
        'smith machine',         'wheel roller',      'stationary bike',
                 'tire',             'trap bar',   'elliptical machine',
     'stepmill machine']
Length: 28, dtype: str

In [196]:
table_body_part = df['bodyPart']
df['bodyPart'].unique()

<StringArray>
[     'waist', 'upper legs',       'back', 'lower legs',      'chest',
 'upper arms',     'cardio',  'shoulders', 'lower arms',       'neck']
Length: 10, dtype: str

In [197]:
df['secondaryMuscles/0'].unique()

<StringArray>
[      'hip flexors',          'obliques',        'hamstrings',
            'biceps', 'ankle stabilizers',           'triceps',
         'shoulders',            'glutes',        'quadriceps',
             'chest',            'calves',          'forearms',
        'lower back',             'traps',        'upper back',
            'ankles',         'trapezius',          'deltoids',
              'core',         'rhomboids',      'rotator cuff',
     'wrist flexors',   'wrist extensors',  'latissimus dorsi',
        'abdominals',              'lats',            'soleus',
            'wrists',             'hands']
Length: 29, dtype: str

In [198]:
# Filtrar as colunas de músculos secundários
secondary_cols = [c for c in df.columns if c.startswith('secondaryMuscles/')]

# Criar uma lista temporária com todos os músculos secundários encontrados
raw_muscles = []
for col in secondary_cols:
    raw_muscles.extend(df[col].dropna().unique().tolist())

# Filtrar elementos únicos, removendo nulos e eventuais strings indesejadas
table_secundary_muscles = sorted(list({
    str(m).strip() for m in raw_muscles
    if pd.notna(m) and str(m).lower() != 'nan' and str(m).strip() != ''
}))

# Exibir a lista limpa
print(table_secundary_muscles)
print(len(table_secundary_muscles))

['abdominals', 'ankle stabilizers', 'ankles', 'back', 'biceps', 'brachialis', 'calves', 'chest', 'core', 'deltoids', 'feet', 'forearms', 'glutes', 'grip muscles', 'groin', 'hamstrings', 'hands', 'hip flexors', 'inner thighs', 'latissimus dorsi', 'lats', 'lower abs', 'lower back', 'obliques', 'quadriceps', 'rear deltoids', 'rhomboids', 'rotator cuff', 'shins', 'shoulders', 'soleus', 'sternocleidomastoid', 'trapezius', 'traps', 'triceps', 'upper back', 'upper chest', 'wrist extensors', 'wrist flexors', 'wrists']
40

## 3. Preparação das entidades

Os valores de equipamento, parte do corpo e músculos secundários são separados para formar tabelas de referência. Em seguida, são gerados IDs e mapas de correspondência para substituir valores repetidos por chaves estrangeiras.

Também é criada a tabela intermediária `exercise_secondary_muscle`, que representa a relação muitos-para-muitos entre exercícios e músculos secundários.

In [199]:
# As tabelas de referência recebem os IDs do banco durante a carga.
# Aqui mantemos apenas os nomes, que serão usados para localizar esses IDs.
unique_body_parts = sorted(df['bodyPart'].dropna().unique())
df_body_part = pd.DataFrame({'name': unique_body_parts})

unique_equipment = sorted(df['equipment'].dropna().unique())
df_equipment = pd.DataFrame({'name': unique_equipment})

df_secondary_muscle = pd.DataFrame({'name': table_secundary_muscles})

# O banco gera o ID dos exercícios. name + gif_url identifica cada registro
# sem depender de IDs criados localmente.
table_exercise = pd.DataFrame({
    'name': df['name'],
    'gif_url': df['gif_url'],
    'instructions_sumarization': df['instructions_sumarization'],
    'body_part_name': df['bodyPart'],
    'equipment_name': df['equipment']
})

exercise_muscle_relations = []
secondary_cols = [c for c in df.columns if c.startswith('secondaryMuscles/')]

for _, row in df.iterrows():
    for col in secondary_cols:
        muscle = row[col]
        if pd.notna(muscle) and str(muscle).strip():
            exercise_muscle_relations.append({
                'exercise_name': row['name'],
                'exercise_gif_url': row['gif_url'],
                'secondary_muscle_name': str(muscle).strip()
            })

df_exercise_secondary_muscle = pd.DataFrame(
    exercise_muscle_relations,
    columns=['exercise_name', 'exercise_gif_url', 'secondary_muscle_name']
).drop_duplicates()

print('--- DataFrames criados para modelagem relacional ---')
print(f'Partes do corpo encontradas: {len(df_body_part)}')
print(f'Equipamentos encontrados: {len(df_equipment)}')
print(f'Músculos secundários encontrados: {len(df_secondary_muscle)}')
print(f'Exercícios preparados: {len(table_exercise)}')
print(f'Relações N-N preparadas: {len(df_exercise_secondary_muscle)}')

display(df_exercise_secondary_muscle.head())

--- DataFrames criados para modelagem relacional ---
Partes do corpo encontradas: 10
Equipamentos encontrados: 28
Músculos secundários encontrados: 40
Exercícios preparados: 1324
Relações N-N preparadas: 2581

,exercise_name,exercise_gif_url,secondary_muscle_name
0,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,hip flexors
1,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,lower back
2,45° side bend,https://v2.exercisedb.io/image/PERWLDGUxVbpHS,obliques
3,air bike,https://v2.exercisedb.io/image/PLr4yo3j-f1amp,hip flexors
4,all fours squad stretch,https://v2.exercisedb.io/image/XPQwM7HECjgNFE,hamstrings

In [200]:
table_exercise

,name,gif_url,instructions_sumarization,body_part_name,equipment_name
0,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,1. Lie flat on your back with your knees bent ...,waist,body weight
1,45° side bend,https://v2.exercisedb.io/image/PERWLDGUxVbpHS,1. Stand with your feet shoulder-width apart a...,waist,body weight
2,air bike,https://v2.exercisedb.io/image/PLr4yo3j-f1amp,1. Lie flat on your back with your hands place...,waist,body weight
3,all fours squad stretch,https://v2.exercisedb.io/image/XPQwM7HECjgNFE,1. Start on all fours with your hands directly...,upper legs,body weight
4,alternate heel touchers,https://v2.exercisedb.io/image/5nYph4eUGNiEdf,1. Lie flat on your back with your knees bent ...,waist,body weight
...,...,...,...,...,...
1319,wide-grip chest dip on high parallel bars,https://v2.exercisedb.io/image/XQn4pU9HRquS2b,1. Position yourself on the parallel bars with...,chest,body weight
1320,wind sprints,https://v2.exercisedb.io/image/ZLPKUAaiObH-2X,1. Find an open space or a track to perform th...,waist,body weight
1321,world greatest stretch,https://v2.exercisedb.io/image/3A5fPe5oCr2EwN,1. Start in a lunge position with your right f...,upper legs,body weight
1322,wrist circles,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,1. Extend your arms straight out in front of y...,lower arms,body weight
1323,wrist rollerer,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,1. Attach a weight to one end of a rope or bar...,lower arms,weighted

In [201]:
df_exercise_secondary_muscle

,exercise_name,exercise_gif_url,secondary_muscle_name
0,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,hip flexors
1,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,lower back
2,45° side bend,https://v2.exercisedb.io/image/PERWLDGUxVbpHS,obliques
3,air bike,https://v2.exercisedb.io/image/PLr4yo3j-f1amp,hip flexors
4,all fours squad stretch,https://v2.exercisedb.io/image/XPQwM7HECjgNFE,hamstrings
...,...,...,...
2576,world greatest stretch,https://v2.exercisedb.io/image/3A5fPe5oCr2EwN,calves
2577,wrist circles,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,hands
2578,wrist circles,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,wrists
2579,wrist rollerer,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,biceps
2580,wrist rollerer,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,triceps

In [202]:
df_exercise_secondary_muscle

,exercise_name,exercise_gif_url,secondary_muscle_name
0,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,hip flexors
1,3/4 sit-up,https://v2.exercisedb.io/image/MOnK4iG0MEt9h8,lower back
2,45° side bend,https://v2.exercisedb.io/image/PERWLDGUxVbpHS,obliques
3,air bike,https://v2.exercisedb.io/image/PLr4yo3j-f1amp,hip flexors
4,all fours squad stretch,https://v2.exercisedb.io/image/XPQwM7HECjgNFE,hamstrings
...,...,...,...
2576,world greatest stretch,https://v2.exercisedb.io/image/3A5fPe5oCr2EwN,calves
2577,wrist circles,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,hands
2578,wrist circles,https://v2.exercisedb.io/image/o8lN2wxaJZIzlF,wrists
2579,wrist rollerer,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,biceps
2580,wrist rollerer,https://v2.exercisedb.io/image/bpHngD4xNKxD6u,triceps

## 4. Criação do esquema no banco

Antes da carga, o script DDL define as tabelas e suas restrições no MySQL. As tabelas de referência são independentes; `exercise` depende de partes do corpo e equipamentos; e a tabela intermediária depende de exercícios e músculos.

Essa estrutura reduz a repetição dos dados e mantém os relacionamentos explícitos por meio de chaves primárias e estrangeiras.

### Scripts de Criação das Tabelas (MySQL DDL)

Antes de rodar o código Python, execute este script SQL no seu cliente MySQL (como Workbench, DBeaver, etc.) para criar o esquema correto com as chaves estrangeiras e a tabela intermediária N-N:

```sql
-- 1. Tabela de Partes do Corpo
CREATE TABLE body_part (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 2. Tabela de Equipamentos
CREATE TABLE equipment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 3. Tabela de Músculos Secundários
CREATE TABLE secondary_muscle (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 4. Tabela de Exercícios (com FKs para body_part e equipment)
CREATE TABLE exercise (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    gif_url VARCHAR(255),
    instructions_sumarization TEXT,
    fk_body_part INT,
    fk_equipment INT,
    FOREIGN KEY (fk_body_part) REFERENCES body_part(id),
    FOREIGN KEY (fk_equipment) REFERENCES equipment(id)
);

-- 5. Tabela Intermediária N-N (Relação Exercício <-> Músculo Secundário)
CREATE TABLE exercise_secondary_muscle (
    exercise_id INT,
    secondary_muscle_id INT,
    PRIMARY KEY (exercise_id, secondary_muscle_id),
    FOREIGN KEY (exercise_id) REFERENCES exercise(id),
    FOREIGN KEY (secondary_muscle_id) REFERENCES secondary_muscle(id)
);
```

## 5. Inserção dos dados no MySQL

A função de carga abre a conexão e grava os DataFrames na ordem exigida pelas dependências do esquema: primeiro as tabelas de referência, depois os exercícios e, por último, a tabela de relacionamento muitos-para-muitos.

O uso de `if_exists='append'` adiciona os registros às tabelas existentes. As credenciais e o banco devem ser configurados no ambiente local antes da execução.

In [203]:
from datetime import datetime
from pathlib import Path
from sqlalchemy import create_engine, text

ETL_SUMMARY_LOG = Path('etl_summary.log')
ETL_ERROR_LOG = Path('etl_errors.log')


def _write_log(path, message):
    timestamp = datetime.now().isoformat(timespec='seconds')
    with path.open('a', encoding='utf-8') as log_file:
        log_file.write(f'[{timestamp}] {message}\n')


def _insert_dimension(connection, table_name, source_frame):
    existing = pd.read_sql_query(
        text(f'SELECT id, name FROM {table_name}'),
        connection
    )
    existing_names = set(existing['name'])
    missing = source_frame.loc[~source_frame['name'].isin(existing_names), ['name']]

    if not missing.empty:
        rows = missing.to_dict('records')
        connection.execute(
            text(f'INSERT INTO {table_name} (name) VALUES (:name)'),
            rows
        )

    current = pd.read_sql_query(
        text(f'SELECT id, name FROM {table_name}'),
        connection
    )
    return current, len(missing)


def insert_data_to_mysql():
    """Carrega o ETL usando IDs gerados pelo banco e registra a execução."""
    
    engine = create_engine(MYSQL_URL)
    summary = []

    try:
        with engine.begin() as connection:
            body_parts, body_inserted = _insert_dimension(
                connection, 'body_part', df_body_part
            )
            summary.append(('body_part', body_inserted, len(df_body_part)))

            equipment, equipment_inserted = _insert_dimension(
                connection, 'equipment', df_equipment
            )
            summary.append(('equipment', equipment_inserted, len(df_equipment)))

            muscles, muscle_inserted = _insert_dimension(
                connection, 'secondary_muscle', df_secondary_muscle
            )
            summary.append(('secondary_muscle', muscle_inserted, len(df_secondary_muscle)))

            body_map = dict(zip(body_parts['name'], body_parts['id']))
            equipment_map = dict(zip(equipment['name'], equipment['id']))
            muscle_map = dict(zip(muscles['name'], muscles['id']))

            exercises = table_exercise.copy()
            exercises['fk_body_part'] = exercises['body_part_name'].map(body_map)
            exercises['fk_equipment'] = exercises['equipment_name'].map(equipment_map)

            if exercises[['fk_body_part', 'fk_equipment']].isna().any().any():
                raise ValueError('Há FKs de exercício sem correspondência nas tabelas de referência.')

            existing_exercises = pd.read_sql_query(
                text('SELECT id, name, gif_url FROM exercise'),
                connection
            )
            existing_exercise_keys = set(zip(existing_exercises['name'], existing_exercises['gif_url']))
            new_exercises = exercises.loc[
                ~exercises.set_index(['name', 'gif_url']).index.isin(existing_exercise_keys),
                ['name', 'gif_url', 'instructions_sumarization', 'fk_body_part', 'fk_equipment']
            ]

            if not new_exercises.empty:
                connection.execute(
                    text('''
                        INSERT INTO exercise
                            (name, gif_url, instructions_sumarization, fk_body_part, fk_equipment)
                        VALUES
                            (:name, :gif_url, :instructions_sumarization, :fk_body_part, :fk_equipment)
                    '''),
                    new_exercises.to_dict('records')
                )

            all_exercises = pd.read_sql_query(
                text('SELECT id, name, gif_url FROM exercise'),
                connection
            )
            exercise_map = dict(zip(zip(all_exercises['name'], all_exercises['gif_url']), all_exercises['id']))
            summary.append(('exercise', len(new_exercises), len(exercises)))

            relations = df_exercise_secondary_muscle.copy()
            relations['exercise_id'] = [
                exercise_map.get((name, gif_url))
                for name, gif_url in zip(
                    relations['exercise_name'], relations['exercise_gif_url']
                )
            ]
            relations['secondary_muscle_id'] = relations['secondary_muscle_name'].map(muscle_map)
            if relations[['exercise_id', 'secondary_muscle_id']].isna().any().any():
                raise ValueError('Há relações N-N sem exercício ou músculo correspondente.')

            relations = relations[['exercise_id', 'secondary_muscle_id']].drop_duplicates()
            existing_relations = pd.read_sql_query(
                text('SELECT exercise_id, secondary_muscle_id FROM exercise_secondary_muscle'),
                connection
            )
            existing_pairs = set(map(tuple, existing_relations.to_numpy()))
            new_relations = [
                row for row in relations.to_dict('records')
                if (row['exercise_id'], row['secondary_muscle_id']) not in existing_pairs
            ]

            if new_relations:
                connection.execute(
                    text('''
                        INSERT INTO exercise_secondary_muscle
                            (exercise_id, secondary_muscle_id)
                        VALUES (:exercise_id, :secondary_muscle_id)
                    '''),
                    new_relations
                )
            summary.append(('exercise_secondary_muscle', len(new_relations), len(relations)))

        _write_log(ETL_SUMMARY_LOG, 'SUCESSO | ' + ' | '.join(
            f'{table}: {inserted}/{total} novas linhas' for table, inserted, total in summary
        ))
        print('[Sucesso] ETL concluído. Resumo salvo em etl_summary.log.')

    except Exception as error:
        _write_log(ETL_ERROR_LOG, f'ERRO | transação revertida | linhas efetivamente inseridas: 0 | {error!r}')
        _write_log(ETL_ERROR_LOG, 'Detalhes | ' + ' | '.join(
            f'{table}: {inserted}/{total} linhas preparadas' for table, inserted, total in summary
        ))
        print('[Erro] ETL revertido pela transação. Detalhes salvos em etl_errors.log.')
        raise
    finally:
        engine.dispose()

# Exemplo:
insert_data_to_mysql()

[Sucesso] ETL concluído. Resumo salvo em etl_summary.log.

## 6. Análise dos dados no banco

Com os dados carregados, as consultas SQL permitem analisar o catálogo sem retornar ao CSV. Cada consulta combina as tabelas normalizadas para responder a uma pergunta específica e usa parâmetros para filtrar os valores escolhidos.

As análises abaixo mostram exercícios por parte do corpo, por conjunto de músculos secundários, por equipamento e por exercícios realizados apenas com o peso corporal.

In [204]:
# Configurar a conexão e um helper para executar consultas SQL
from sqlalchemy import create_engine, text
import os


engine = create_engine(MYSQL_URL) if MYSQL_URL else None

def run_sql(query, params=None):
    if engine is None:
        raise RuntimeError(
            "Defina a variável de ambiente MYSQL_URL antes de executar as consultas. "
            "Exemplo: mysql+pymysql://usuario:senha@localhost:3306/spring_api_system"
        )
    return pd.read_sql_query(text(query), con=engine, params=params or {})

# Exemplo no PowerShell, antes de abrir o notebook:
# $env:MYSQL_URL = 'mysql+pymysql://usuario:senha@localhost:3306/spring_api_system'

# Filtrar exercícios de determinada parte do corpo
body_part = 'chest'
query_body_part = """
SELECT
    e.id,
    e.name,
    e.gif_url,
    e.instructions_sumarization,
    bp.name AS body_part,
    eq.name AS equipment
FROM exercise AS e
JOIN body_part AS bp ON bp.id = e.fk_body_part
LEFT JOIN equipment AS eq ON eq.id = e.fk_equipment
WHERE bp.name = :body_part
ORDER BY e.name;
"""

exercises_by_body_part = run_sql(query_body_part, {'body_part': body_part})
exercises_by_body_part

,id,name,gif_url,instructions_sumarization,body_part,equipment
0,9,archer push up,https://v2.exercisedb.io/image/GSjHZGSiL1VbQ7,1. Start in a push-up position with your hands...,chest,body weight
1,14,assisted chest dip (kneeling),https://v2.exercisedb.io/image/AbxK1fjW5YdIBj,1. Adjust the machine to your desired height a...,chest,leverage machine
2,28,assisted seated pectoralis major stretch with ...,https://v2.exercisedb.io/image/V4PlYYE0rlK7tY,1. Sit on a stability ball with your feet flat...,chest,assisted
3,35,assisted wide-grip chest dip (kneeling),https://v2.exercisedb.io/image/9RWiaQoGBGogXv,1. Adjust the machine to your desired height a...,chest,leverage machine
4,47,band bench press,https://v2.exercisedb.io/image/oyWqo0D8zSMbyD,1. Lie flat on a bench with your feet flat on ...,chest,band
...,...,...,...,...,...,...
158,1286,weighted drop push up,https://v2.exercisedb.io/image/E8J5-cePYrT9wV,1. Start in a high plank position with your ha...,chest,weighted
159,1309,weighted straight bar dip,https://v2.exercisedb.io/image/AkggKC6OQge0F2,1. Position yourself between parallel bars wit...,chest,weighted
160,1311,weighted svend press,https://v2.exercisedb.io/image/kzCVhNDLZqZhEv,1. Stand with your feet shoulder-width apart a...,chest,weighted
161,1319,wide hand push up,https://v2.exercisedb.io/image/MHvTGUQzgYIdCi,1. Start in a high plank position with your ha...,chest,body weight
162,1320,wide-grip chest dip on high parallel bars,https://v2.exercisedb.io/image/XQn4pU9HRquS2b,1. Position yourself on the parallel bars with...,chest,body weight

In [205]:
# Filtrar exercícios que trabalhem todos os grupos musculares secundários informados
secondary_muscles = ['triceps', 'shoulders']

if not secondary_muscles:
    raise ValueError('Informe pelo menos um músculo secundário.')

muscle_placeholders = ', '.join(
    f':muscle_{index}' for index in range(len(secondary_muscles))
)
muscle_params = {
    f'muscle_{index}': muscle
    for index, muscle in enumerate(secondary_muscles)
}

query_secondary_muscles = f"""
SELECT
    e.id,
    e.name,
    e.gif_url,
    bp.name AS body_part,
    eq.name AS equipment,
    COUNT(DISTINCT sm.name) AS matched_muscles
FROM exercise AS e
JOIN exercise_secondary_muscle AS esm
    ON esm.exercise_id = e.id
JOIN secondary_muscle AS sm
    ON sm.id = esm.secondary_muscle_id
LEFT JOIN body_part AS bp
    ON bp.id = e.fk_body_part
LEFT JOIN equipment AS eq
    ON eq.id = e.fk_equipment
WHERE sm.name IN ({muscle_placeholders})
GROUP BY e.id, e.name, e.gif_url, bp.name, eq.name
HAVING COUNT(DISTINCT sm.name) = {len(secondary_muscles)}
ORDER BY e.name;
"""

if engine is not None:
    exercises_by_secondary_muscles = run_sql(query_secondary_muscles, muscle_params)
    display(exercises_by_secondary_muscles)
else:
    print('MYSQL_URL não configurada. A consulta está pronta para execução.')

,id,name,gif_url,body_part,equipment,matched_muscles
0,9,archer push up,https://v2.exercisedb.io/image/GSjHZGSiL1VbQ7,chest,body weight,2
1,14,assisted chest dip (kneeling),https://v2.exercisedb.io/image/AbxK1fjW5YdIBj,chest,leverage machine,2
2,28,assisted seated pectoralis major stretch with ...,https://v2.exercisedb.io/image/V4PlYYE0rlK7tY,chest,assisted,2
3,35,assisted wide-grip chest dip (kneeling),https://v2.exercisedb.io/image/9RWiaQoGBGogXv,chest,leverage machine,2
4,47,band bench press,https://v2.exercisedb.io/image/oyWqo0D8zSMbyD,chest,band,2
...,...,...,...,...,...,...
150,1294,weighted muscle up (on bar),https://v2.exercisedb.io/image/IPG2VufiEtv7C9,back,weighted,2
151,1309,weighted straight bar dip,https://v2.exercisedb.io/image/AkggKC6OQge0F2,chest,weighted,2
152,1311,weighted svend press,https://v2.exercisedb.io/image/kzCVhNDLZqZhEv,chest,weighted,2
153,1319,wide hand push up,https://v2.exercisedb.io/image/MHvTGUQzgYIdCi,chest,body weight,2
154,1320,wide-grip chest dip on high parallel bars,https://v2.exercisedb.io/image/XQn4pU9HRquS2b,chest,body weight,2

In [206]:
# Filtrar exercícios que usam equipamentos específicos
selected_equipment = ['barbell', 'dumbbell', 'cable']

equipment_placeholders = ', '.join(
    f':equipment_{index}' for index in range(len(selected_equipment))
)
equipment_params = {
    f'equipment_{index}': equipment
    for index, equipment in enumerate(selected_equipment)
}

query_equipment = f"""
SELECT
    e.id,
    e.name,
    e.gif_url,
    bp.name AS body_part,
    eq.name AS equipment
FROM exercise AS e
JOIN equipment AS eq ON eq.id = e.fk_equipment
LEFT JOIN body_part AS bp ON bp.id = e.fk_body_part
WHERE eq.name IN ({equipment_placeholders})
ORDER BY eq.name, e.name;
"""

if engine is not None:
    exercises_by_equipment = run_sql(query_equipment, equipment_params)
    display(exercises_by_equipment)
else:
    print('MYSQL_URL não configurada. A consulta está pronta para execução.')

,id,name,gif_url,body_part,equipment
0,97,barbell alternate biceps curl,https://v2.exercisedb.io/image/6eatsU45zhybk2,upper arms,barbell
1,98,barbell bench front squat,https://v2.exercisedb.io/image/74DX1mCZgri99f,upper legs,barbell
2,99,barbell bench press,https://v2.exercisedb.io/image/ZZPby9wkLJSFcL,chest,barbell
3,100,barbell bench squat,https://v2.exercisedb.io/image/RaH8qnuehbXUKO,upper legs,barbell
4,101,barbell bent arm pullover,https://v2.exercisedb.io/image/w3qIda45giizel,back,barbell
...,...,...,...,...,...
600,796,farmers walk,https://v2.exercisedb.io/image/bZAhYGdE30zMgp,upper legs,dumbbell
601,840,hyght dumbbell fly,https://v2.exercisedb.io/image/huwzqYLi5K6Ldx,chest,dumbbell
602,1070,push-up close-grip off dumbbell,https://v2.exercisedb.io/image/6ALCB8nIBWeTQO,upper arms,dumbbell
603,1147,single leg calf raise (on a dumbbell),https://v2.exercisedb.io/image/j9Gci9VUbd0tlv,lower legs,dumbbell
604,1220,spell caster,https://v2.exercisedb.io/image/YlrvBmGzv6WJmX,waist,dumbbell

In [207]:
# Filtrar exercícios de calistenia: resistência do próprio corpo, sem equipamento externo
query_bodyweight = """
SELECT
    e.id,
    e.name,
    e.gif_url,
    bp.name AS body_part,
    eq.name AS equipment
FROM exercise AS e
JOIN equipment AS eq ON eq.id = e.fk_equipment
LEFT JOIN body_part AS bp ON bp.id = e.fk_body_part
WHERE eq.name = 'body weight'
ORDER BY bp.name, e.name;
"""

if engine is not None:
    bodyweight_exercises = run_sql(query_bodyweight)
    display(bodyweight_exercises)
else:
    print('MYSQL_URL não configurada. A consulta está pronta para execução.')

,id,name,gif_url,body_part,equipment
0,8,archer pull up,https://v2.exercisedb.io/image/LSBkdKcbK4xj8n,back,body weight
1,39,back lever,https://v2.exercisedb.io/image/tbNQwmPPyh4Eds,back,body weight
2,40,back pec stretch,https://v2.exercisedb.io/image/RWvKeWqoM6lpAb,back,body weight
3,245,bench pull-ups,https://v2.exercisedb.io/image/jBAdgotsMCRHN0,back,body weight
4,255,bodyweight squatting row,https://v2.exercisedb.io/image/LayT4WNa4tHO0Q,back,body weight
...,...,...,...,...,...
320,1268,twisted leg raise,https://v2.exercisedb.io/image/cz2udtwSpKiadv,waist,body weight
321,1269,twisted leg raise (female),https://v2.exercisedb.io/image/xfSZbjuVqOQiIa,waist,body weight
322,1273,v-sit on floor,https://v2.exercisedb.io/image/pm-IAuoY54IN1X,waist,body weight
323,1274,vertical leg raise (on parallel bars),https://v2.exercisedb.io/image/neOsgRGSLAlQdw,waist,body weight
324,1321,wind sprints,https://v2.exercisedb.io/image/ZLPKUAaiObH-2X,waist,body weight

In [208]:
# Listar todos os equipamentos e classificar o tipo de resistência
query_equipment_classification = """
SELECT
    id,
    name AS equipment,
    CASE
        WHEN name = 'body weight' THEN 'somente o próprio corpo'
        WHEN name = 'assisted' THEN 'assistência externa'
        WHEN name = 'weighted' THEN 'carga externa'
        ELSE 'equipamento externo'
    END AS equipment_type
FROM equipment
ORDER BY
    CASE
        WHEN name = 'body weight' THEN 1
        WHEN name IN ('assisted', 'weighted') THEN 2
        ELSE 3
    END,
    name;
"""

if engine is not None:
    equipment_classification = run_sql(query_equipment_classification)
    display(equipment_classification)
else:
    print('MYSQL_URL não configurada. A consulta está pronta para execução.')

    id             equipment           equipment_type
0    4           body weight  somente o próprio corpo
1    1              assisted      assistência externa
2   27              weighted            carga externa
3    2                  band      equipamento externo
4    3               barbell      equipamento externo
5    5             bosu ball      equipamento externo
6    6                 cable      equipamento externo
7    7              dumbbell      equipamento externo
8    8    elliptical machine      equipamento externo
9    9            ez barbell      equipamento externo
10  10                hammer      equipamento externo
11  11            kettlebell      equipamento externo
12  12      leverage machine      equipamento externo
13  13         medicine ball      equipamento externo
14  14       olympic barbell      equipamento externo
15  15       resistance band      equipamento externo
16  16                roller      equipamento externo
17  17                  rope      equipamento externo
18  18        skierg machine      equipamento externo
19  19          sled machine      equipamento externo
20  20         smith machine      equipamento externo
21  21        stability ball      equipamento externo
22  22       stationary bike      equipamento externo
23  23      stepmill machine      equipamento externo
24  24                  tire      equipamento externo
25  25              trap bar      equipamento externo
26  26  upper body ergometer      equipamento externo
27  28          wheel roller      equipamento externo